### ISSUE TITLE
Logging as debug instead of info?

### ISSUE THREAD

**Issue by PR-O** [schaloner/deadbolt-2-java#11]
Hi there,

We've recently switched our Playframework app Log level to INFO for development. In case we encounter serious bugs, we switch to DEBUG mode.

With the Log level at INFO, about 1/3 of our log is filled with Deadbolt messages like this one:

        [info] b.o.d.j.a.AbstractDeadboltAction - Getting Deadbolt handler with key [defaultHandler]

It's generated by the [AbstractDeadBoltAction](https://github.com/schaloner/deadbolt-2-java/blob/master/code/app/be/objectify/deadbolt/java/actions/AbstractDeadboltAction.java), line 77:

        LOGGER.info("Getting Deadbolt handler with key [{}]", handlerKey);

You're probably guessing where this is going... I'm wondering if we can either:
- expose a Deadbolt LOG LEVEL config variable
- move log statements like the one above to the DEBUG level

**Comment by schaloner** [comment]
Which version of Deadbolt are you using?

**Comment by PR-O** [comment]
2.4.0

**Comment by schaloner** [comment]
I'll go through the code and tinker with the loggnig calls.  In the meantime, you should be able to change the logging level specifically for AbstractDeadboltAction in the log config file (it uses slf4j).

**Comment by PR-O** [comment]
Cool.

I completely forgot about the slf4j config! Nice, I'll configure the logging rule right now.

**Comment by schaloner** [comment]
Can I close this?

**Comment by PR-O** [comment]
Yes, go ahead!

**Comment by PR-O** [comment]
Or better yet, I'll close it.
