### ISSUE TITLE
How the get Subject *within* Controller method?

### ISSUE THREAD

**Issue by dEajL3kA** [schaloner/deadbolt-2-java#114]
If I use annotations like `@SubjectPresent` on my controller method, then the `getSubject()` method of my DeadboltHandler implementation is invoked automatically. Dependning on whether a subject was returned or not, the controller method is either allowed to run or not. If the controller method *is* allowed to run: How to get the subject ***within*** the controller method?

```
public class MyController extends Controller
{
    @SubjectPresent
    public CompletionStage<Result> search()
    {
        final Subject subject = DeadboltUtils.getCurrentSubject(); /* <-- I need something like this !!! */
    }
}
```

I found the recommendation that the `getSubject()` method should store the Subject in `HttpContext.args`, but this is **no** longer possible in Play Framework 2.7 and newer, because `HttpContext.args` has been *remvoed* by now 😞 

(Also `HttpRequest.attrs` is **not** an alternative, because it is immutable)

Best regards.

**Comment by poirierlouis** [comment]
Hi,

As `HttpContext` is no longer exposed, storing Subject using `args` is now a no go. However, you can add information in client's session:

```java
class Authentication extends Controller {

  public Result login(final Http.Request request) {
    // ...
    Subject subject = null; // get subject

    return ok().addingToSession(request, "id", subject.id)
               .addingToSession(request, "role", subject.role.getName());
  }

}
```

You can then read session's keys when you need it using `Http.Request`. It might look something like:
```java
class MyController extends Controller {

  private final SubjectRepository subjectRepository;

  @Inject
  public MyController(final SubjectRepository subjectRepository) {
    this.subjectRepository = subjectRepository;
  }

  @SubjectPresent
  public CompletionStage<Result> search(final Http.Request request) {
    String id = request.session().getOptional("id").orElse(null);
    String role = request.session().getOptional("role").orElse(null);

    return subjectRepository.findById(id).thenApplyAsync((subject) -> {
    }).thenComposeAsync(subjectRepository.search(), (subject, data) -> {
      return ok(data);
    });
  }
}
```
Note that you might not want / need to request Subject entity from a database, but only use id / role fields to test against for access rights (if `@Restrict` is not enough for example).

It is safe as mentioned in [official documentation](https://www.playframework.com/documentation/2.8.x/JavaSessionFlash).
However using a cache mechanism might be a better solution.
