### ISSUE TITLE
Template Restrict error

### ISSUE THREAD

**Issue by ntenisOT** [schaloner/deadbolt-2-java#18]
First of all thanks for the awesome module and the examples.

In your Quickstart for Java you state that:

    @import be.objectify.deadbolt.core.utils.TemplateUtils.{la, as}

is required but I found from your example that both lines below are required. Can you please update the Quickstart?

    @import be.objectify.deadbolt.java.views.html.{restrict, restrictOr}
    @import be.objectify.deadbolt.core.utils.TemplateUtils.{la, as}

**Comment by schaloner** [comment]
Thanks - I've corrected the quickstart.
