### ISSUE TITLE
Allow assigning permissions via roles

### ISSUE THREAD

**Issue by benmccann** [schaloner/deadbolt-2-java#24]
Typically in an RBAC system you can assign someone a role and that assigns some set of permissions to them. You shouldn't generally do checks that require a given role to take an action. E.g. if you want the application administrator to have the ability to create a new role and assign it some set of permissions you can't do that with Deadbolt

**Comment by schaloner** [comment]
Sorry for the delay; GitHub could use a vacation auto-responder.

I'll have a think about this.  All the pieces are there, just no way to conveniently link them.

**Comment by schaloner** [comment]
@benmccann is something like what's described in the attached patch what you're looking for?  This allows the existing support for roles and permissions, with permissions associated with roles applied like this:

    @RoleBasedPermissions("roleName")
    public CompletionStage<Result> someControllerMethod() 
    {
        ...
    }

The role name is used to get the associated permissions from the DeadboltHandler via a new method:

    public interface DeadboltHandler
    {
        // existing methods
        
        /**
         * Get the permissions associated with a role.
         *
         * @param roleName the role the permissions are associated with
         * @return a non-null list containing the permissions associated with the role
         */
        default List<? extends Permission> getPermissionsForRole(String roleName)
        {
            return Collections.emptyList();
        }
    }

[deadbolt-2-java-24.zip](https://github.com/schaloner/deadbolt-2-java/files/383454/deadbolt-2-java-24.zip)

**Comment by benmccann** [comment]
Yes, something like `getPermissionsForRole` is exactly what I was looking for! Thank you!

I'm not quite sure how `@RoleBasedPermissions("roleName")` is different from `@Restrict(@Group("roleName"))`. I'm not sure it's needed in any case. When doing authorization against a controller, I would want to check permissions instead of roles. I think that's already supported:

    @Pattern("admin.printer")
    public CompletionStage<Result> someControllerMethod() 
    {
        ...
    }

**Comment by schaloner** [comment]
`@Restrict` checks on the roles the subject has.

`@Pattern` checks on the permissions has.

`RoleBasedPermissions` introduces a layer of indirection, using the role as a key for a set of permissions assigned to it. 

I'm not convinced of the use of roles here; it may confuse the issue.  In the example implementation, for example, the annotation name implies to me that a user must have the role and at least one of the permissions assigned to that role; in fact, the role name isn't linked to a Deadbolt `Role` in any way.

Would you be OK with a clearer nomenclature that makes it clear the key is an alias for a group of permissions?

**Comment by benmccann** [comment]
I'm having a difficult time understanding your last comment. I think there's a chance we're using "role" to mean different things, so just to be clear, I'll explain how I've always seen "role", "permission", and "subject" used. E.g. here's a slide I found that explains how role based access control works in Angular. I just picked Angular because it was the first example I found, but this is the most standard way for auth systems to be setup. Typically a user is assigned a role which grants them a set of permissions. When accessing a resource, the system does a check to see if the subject has the required permission. I'm not sure if you're using role in some other sense?

![angularjs-security-defend-your-single-page-application-55-638](https://cloud.githubusercontent.com/assets/322311/17155354/9afbb3aa-5339-11e6-932b-ea89416b9d67.jpg)

>In the example implementation, for example

Which example? The `@RoleBasedPermissions("roleName")` example you posted or the `@Pattern("admin.printer")` example I posted?

**Comment by schaloner** [comment]
At the moment, roles and permissions are separate concepts.  Roles do not imply permissions, and vice versa.  

Roles are inherently tied to `Restrict` (both at controller and view level), so when `@Restrict` is used it basically uses `Subject#getRoles` and looks if the subject has the required role.  If multiple (i.e. AND) or alternative (i.e. OR) relationships are defined - let's say `@Restrict(@Group({"admin", "printer"}))`, in which a subject must have the `(admin AND printer)` roles - that is also handled.  This is done through a straightforward comparison of the required role name and the name of the roles the subject has, obtained via `Role#getName`.

Permissions are inherently tied to `Pattern`, and allow for greater granularity.  The `Pattern` constraint uses `Subject#getPermissions` and matches e.g. `@Pattern("admin.printer")` against the subject's permissions.

Let's assume a company that has various departments, e.g. IT support, public relations, etc, and take two subjects.

Subject A has been assigned the following:
* Roles
 * `admin`
 * `pr`
* Permissions
 * `admin.pr.blog.post.create`
 * `admin.pr.blog.post.delete`
 * `admin.pr.blog.post.update`

Subject B has been assigned the following:
* Roles
 * `admin`
 * `it`
* Permissions
 * `admin.it.printer`
 * `admin.it.ldap`
 * `admin.it.router`

A controller action annotated with `@Restrict(@Group("admin"))` would be accessible to both subject A and subject B, even though they are admins in different departments.  To restrict the action to admins of the IT department, you would need to use `@Restrict(@Group({"admin", "it"}))`.

A controller action annotated with `@Pattern("admin.*")` would be accessible to both subject A and subject B, even though they are admins in different departments.  To restrict the action to admins of the IT department, you would need to use `@Pattern("admin.it.*")`.

However - and here's the important bit - removing the `admin` role from a user would deny them access to actions marked with `@Restrict(@Group("admin"))` but still allow them access to actions marked with `@Pattern("admin.*")`.

The reason for this is I didn't want Deadbolt to be overly opinionated.

>  In the example implementation, for example

I meant my example implementation from the patch.  The approach here is:
* an action is constrained to a role specified using e.g. `@RoleBasedPermissions("admin")`
* the Deadbolt handler is used to get the permissions associated with the `admin` role, using `DeadboltHandler#getPermissionsForRole`
* the permissions explicitly obtained from `Subject#getPermissions` must provide a match

This still doesn't provide a mechanism for assigning those permissions to a subject when a role is assigned, but my feeling here is this logic should be handled by the application itself.  This could be done by injecting the handler cache into your user management code, which can then be used to obtain the default handler, and when a subject is given a role, use `DeadboltHandler#getPermissionsForRole` to find out which permissions to assign the subject at the same time.  This make a small assumption: even if you have multiple handlers, the result of `DeadboltHandler#getPermissionsForRole` would always be the same for any given role.

Equally, when removing a role from a subject, `DeadboltHandler#getPermissionsForRole` could be used to determine the subset of permissions to remove from the subject, e.g. (permissions of removed role) \ (permissions of all other roles held by subject).

**Comment by schaloner** [comment]
This is available in version 2.5.1, released on 05/08/2016.

**Comment by DuongVanTien** [comment]
Hi @schaloner , please!
How to set permission for role?
----------------------------
Let's assume that a role foo gives these permissions:
admin.pr.blog.post.create
admin.pr.blog.post.delete
admin.pr.blog.post.update
admin.pr.twitter.post
