### ISSUE TITLE
Missing parentheses in doc

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2-java#26]
Here: https://deadbolt-java.readme.io/docs/template-constraints
you have:
```
Scala
@subjectPresentOr {
  this is protected
} {
  this will be shown if the constraint blocks the other content
}
```
and should be:
```
Scala
@subjectPresentOr() {
  this is protected
} {
  this will be shown if the constraint blocks the other content
}
```

I'd also add example of ```MyDeadboltHandler``` which can extend ```AbstractDeadboltHandler``` for clarity (because I needed to look for example implementation in the source code)

**Comment by schaloner** [comment]
Docs updated, thanks for the report.
