### ISSUE TITLE
The 'meta' specified in the @Composite is not passed on to the sub constraints.

### ISSUE THREAD

**Issue by rishabh9** [schaloner/deadbolt-2-java#32]
The meta value specified at the controller on a Composite constraint
```
    @Composite(value = "isDevAndOwner", meta = "skip")
    public Result updateResource(String installationId) { /* ... */ }
```
is not available to the dynamic constraint (DynamicResourceHandler) which is sub constraint of the composite constraint:
```
// ...
    @Inject
    public CompositeConstraints(final CompositeCache compositeCache, final ConstraintBuilders builders) {
        final Constraint isDevAndOwner = new ConstraintTree(
                Operator.AND,
                builders.restrict(builders.anyOf(builders.allOf(ROLE_DEVELOPER))).build(),
                builders.dynamic("isResourceOwner").build()
        );
// ...
```
```
public class IsResourceOwner implements DynamicResourceHandler {

    @Override
    public CompletionStage<Boolean> isAllowed(String name, Optional<String> meta, DeadboltHandler deadboltHandler, Http.Context context) {
            return CompletableFuture.supplyAsync(() -> meta.isPresent()); // always false!
    }

// ...
}
```
Do let me know what other details you require or if I am doing something wrong.

**Comment by schaloner** [comment]
This is a bug.  I'll fix it and release 2.5.4 asap.

**Comment by rishabh9** [comment]
Thanks @schaloner for the quick response. Could you please let me know when I can expect 2.5.4 release? Just want to know if it would be in a couple of days or longer so that I can plan on using an alternative to Composite constraints or hold on to it while the bug is fixed. Thanks again.

**Comment by schaloner** [comment]
It should be released within the next 12 hours.

**Comment by rishabh9** [comment]
Awesome! :raised_hands: Thanks again! :smile:

**Comment by schaloner** [comment]
This is released as 2.5.4.

There's also a new property on [Composite](https://github.com/schaloner/deadbolt-2-java/blob/master/code/app/be/objectify/deadbolt/java/actions/Composite.java#L78) that instructs on preferred metadata.

If set to true, the metadata defined in the Composite annotation is given priority over metadata defined directly on the constraint.  So, if you have a constraint tree that contains three `Dynamic` constraints that may have a metadata value defined (let's say `Some("a")`, `None` and `Some("c")`) but want these metadata to be replaced with the metadata defined in `@Composite(value = "isDevAndOwner", meta = "skip")` when evaluating, change the annotation to `@Composite(value = "isDevAndOwner", meta = "skip", preferGlobalMeta = true)`.

If you only want this global value to be used if there isn't metadata in the individual , set it to false.  For the case described above, the first constraint would use `Some("a")`, the second would get `Some("skip")` from the Composite annotation and the third would get `Some("c")`. 

By default, this value is false, giving priority to per-constraint metadata.

**Comment by rishabh9** [comment]
Thanks @schaloner. I downloading 2.5.4 now. Will test and update you in sometime.

**Comment by rishabh9** [comment]
This is working for me. I'll close it. Thanks.
