### ISSUE TITLE
@Pattern and @Restrict actions never get called

### ISSUE THREAD

**Issue by istvano** [schaloner/deadbolt-2-java#5]
Hi,

I have an interesting problem I am running play 2.3

SubjectPresent and SubjectNotPresent both work very well. 
Although no matter how I mark my actions with Restrict and Pattern annotations they do not get triggered.

is there something in the docs I am missing ?
is there a way to debug this ? I enabled logging but as far as I can see there is no logging in the classes. 

My deadbolt config is
deadbolt {
  before-auth-check-timeout=4000,
  java {
    cache-user=true,
	handler=security.HttpHeaderDeadboltHandler
    handlers {
      defaultHandler=security.HttpHeaderDeadboltHandler
    }
  }
}

10000:be.objectify.deadbolt.java.DeadboltPlugin

"be.objectify" %% "deadbolt-java" % "2.3.1",
and
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.7")

Thanks in advance.

**Comment by schaloner** [comment]
Could you post your implemention of security.HttpHeaderDeadboltHandler?

Incidentally, "handler" is an alias for "handlers.defaultHandler" - you don't need to define both.

**Comment by istvano** [comment]
Hi, 

Thanks for having a look! I am not sure what is wrong. Also my getSubject is blocking is there a way to make that non-blocking ?

public class HttpHeaderDeadboltHandler extends AbstractDeadboltHandler {

    private UserProvider provider = null;

    public HttpHeaderDeadboltHandler() {
        provider = new HeaderUserProvider();
    }
    /**
     * Validates if the remote user header is present in the request
     */
    @Override
    public F.Promise<Result> beforeAuthCheck(Http.Context context) {

        String header = HeaderUserProvider.getRemoteUserHeader();

        if ( context.request().headers().containsKey(header) ) {
            return F.Promise.pure(null);
        } else {
            Logger.error("Missing {} header in current request", header);
            for ( String key : context.request().headers().keySet()) {
                Logger.debug("Header [{}] => {}", key, context.request().headers().getOrDefault(key, new String[] {""} )[0]);
            }

            return F.Promise.promise(new F.Function0<Result>()
            {
                @Override
                public Result apply() throws Throwable {
                    String error = Messages.get("errors.missingHeader");
                    return forbidden(error);
                }
            });

        }
    }

    @Override
    public Subject getSubject(Http.Context context)
    {

        User user = provider.getUser(context);
        Logger.debug("Auth - getSubject - {}",user);

        return user;
    }

    @Override
    public F.Promise<Result> onAuthFailure(Http.Context context,
                                                 String content)
    {
        // you can return any result from here - forbidden, etc
        Logger.warn("Auth - onAuthFailure - Authentication failure");
        return F.Promise.promise(new F.Function0<Result>()
        {
            @Override
            public Result apply() throws Throwable {
                String error = Messages.get("errors.notAuthorized");
                return forbidden(error);
            }
        });
    }



}

**Comment by kstubbs04** [comment]
@schaloner I've encountered the exact same issue.  My is exactly as @istvano with the exception that I'm running play 2.3.10.  I get the following stack trace:

	[debug] application - result = null
	[debug] application - creating controller: be.objectify.deadbolt.java.actions.SubjectPresentAction
	[debug] application - result = null
	[debug] application - creating controller: be.objectify.deadbolt.java.actions.RestrictAction
	[error] play - Cannot invoke the action, eventually got an error: java.lang.NullPointerException
	[error] application -

	! @6ooffoif2 - Internal server error, for (GET) [/distributors] ->

	play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
		at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.10.jar:2.3.10]
		at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.10.jar:2.3.10]
		at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.10.jar:2.3.10]
		at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.10.jar:2.3.10]
		at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	Caused by: java.lang.NullPointerException: null
		at be.objectify.deadbolt.java.actions.AbstractRestrictiveAction.execute(AbstractRestrictiveAction.java:42) ~[deadbolt-java_2.11-2.3.3.jar:2.3.3]
		at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:124) ~[deadbolt-java_2.11-2.3.3.jar:2.3.3]
		at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[play_2.11-2.3.10.jar:2.3.10]
		at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[play_2.11-2.3.10.jar:2.3.10]
		at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.1.jar:na]


I'm using a dynamic resource handler that checks for the respective roles and permissions belonging to a subject but it would be nice to have the @restrict and @pattern annotations.  Hope this helps

**Comment by schaloner** [comment]
Can you add a breakpoint at the following location, and check that
* `deadboltHandler` is not null
* `beforeAuthCheck` returns a promise and not null

https://github.com/schaloner/deadbolt-2-java/blob/54754e08eba86c72655ff6d1c9590df681261901/code/app/be/objectify/deadbolt/java/actions/AbstractDeadboltAction.java#L321

**Comment by kstubbs04** [comment]
@schaloner deadboltHandler was not null however beforeAuthCheck was returning null instead of a promise.  Thanks for the assist and keep up the excellent work
