### ISSUE TITLE
ERROR at clean dist

### ISSUE THREAD

**Issue by hideki22** [schaloner/deadbolt-2-java#54]
Hello,

I am opting an error when clean dist, javadoc fail in deadbolt2 class.
```

[error]  app/security/HandlerQualifiers.java:17: inner classes cannot be classfile annotations
[error]     public @interface MainHandler{}
[error]                       ^

```

This error produce when generate javadoc, and don't generate zip with deploy contents.

```
[info] No documentation generated with unsuccessful compiler run
[error] one error found
[error] (compile:doc) Scaladoc generation failed
[error] Total time: 21 s, completed 30-oct-2017 11:44:17
```

Class contains

```
public class HandlerQualifiers {
    @Retention(RetentionPolicy.RUNTIME)
    @Target({ElementType.TYPE, ElementType.PARAMETER})
    @BindingAnnotation
    public @interface MainHandler{}
}
```

What are doing wrong?

Thanks.

**Comment by mkurz** [comment]
@hideki22 This is has nothing to do with deadbolt itself. This is a Scala bug: https://github.com/scala/scala-dev/issues/249
To work around this problem put this into your `build.sbt` file:
```scala
scalacOptions in (Compile, doc) += "-no-java-comments"
```
Also see http://www.scala-lang.org/news/2.12.0/#scaladoc-can-be-used-to-document-java-sources
