### ISSUE TITLE
RoleBasedPermissions are not consistent with Restrict

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2-java#85]
Normally I'm using `@Restrict(@Group("MY_ROLE"))` but when I replaced it to `@RoleBasedPermissions("MY_ROLE")` it always enters to `onAuthFailure`

**Comment by mkurz** [comment]
Did you implement/override `getPermissionsForRole`?
Which permissions does the subject of that request have? Does it match a permission returned by `getPermissionsForRole("MY_ROLE")`?

**Comment by mkurz** [comment]
Also `@Restrict(@Group("MY_ROLE"))` does not have to be consistent with `RoleBasedPermissions` - they check for two different things.

`@Restrict(@Group("MY_ROLE"))` "just" checks of the subject has the role `MY_ROLE`, nothing more.
`@RoleBasedPermissions("MY_ROLE")` does not check for the role of the subject itself, but checks if the subject has a permisson that matches one of the permissions returned by your deadbolt handler `getPermissionsForRole("MY_ROLE")` method.

**Comment by eximius313** [comment]
omg, I just realized, that I misunderstood it as "RoleBased**Restrictions**".
thanks for clarification
