### ISSUE TITLE
Upgrade to Play 2.4.0

### ISSUE THREAD

**Issue by seantbrady** [schaloner/deadbolt-2-java#9]
Play 2.4.0 was released this week.  Will Deadbolt have a release to match?

**Comment by schaloner** [comment]
It's ongoing at the moment.  I'll keep you updated.

**Comment by seantbrady** [comment]
Much appreciated.

**Comment by schaloner** [comment]
`"be.objectify" %% "deadbolt-java" % "2.4.0-SNAPSHOT"` should give what you you're looking for.  Documentation coming later today, but the release notes on https://github.com/schaloner/deadbolt-2-java should be enough to get you started.  All feedback appreciated!

**Comment by schaloner** [comment]
https://github.com/schaloner/deadbolt-2-java-examples has been updated for the latest version.  The Scala version will be updated later today.

**Comment by seantbrady** [comment]
Thanks, Steve!
